2025-03-11 16:14:39,421 INFO    MainThread:25652 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-11 16:14:39,421 INFO    MainThread:25652 [wandb_setup.py:_flush():67] Configure stats pid to 25652
2025-03-11 16:14:39,421 INFO    MainThread:25652 [wandb_setup.py:_flush():67] Loading settings from C:\Users\hause\.config\wandb\settings
2025-03-11 16:14:39,421 INFO    MainThread:25652 [wandb_setup.py:_flush():67] Loading settings from c:\Users\hause\OneDrive\01_Studium\02_Master\05_Masterarbeit\01_PlayerDetection\code\wandb\settings
2025-03-11 16:14:39,421 INFO    MainThread:25652 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-11 16:14:39,422 INFO    MainThread:25652 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\hause\OneDrive\01_Studium\02_Master\05_Masterarbeit\01_PlayerDetection\code\wandb\run-20250311_161439-efgo31en\logs\debug.log
2025-03-11 16:14:39,423 INFO    MainThread:25652 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\hause\OneDrive\01_Studium\02_Master\05_Masterarbeit\01_PlayerDetection\code\wandb\run-20250311_161439-efgo31en\logs\debug-internal.log
2025-03-11 16:14:39,423 INFO    MainThread:25652 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001E5D45AC0D0>
2025-03-11 16:14:39,423 INFO    MainThread:25652 [wandb_init.py:init():761] calling init triggers
2025-03-11 16:14:39,423 INFO    MainThread:25652 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-11 16:14:39,423 INFO    MainThread:25652 [wandb_init.py:init():784] starting backend
2025-03-11 16:14:39,423 INFO    MainThread:25652 [wandb_init.py:init():788] sending inform_init request
2025-03-11 16:14:39,443 INFO    MainThread:25652 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2025-03-11 16:14:39,443 INFO    MainThread:25652 [wandb_init.py:init():803] backend started and connected
2025-03-11 16:14:39,448 INFO    MainThread:25652 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-03-11 16:14:39,457 INFO    MainThread:25652 [wandb_run.py:_label_probe_notebook():1214] Unable to probe notebook: 'charmap' codec can't decode byte 0x8d in position 5509: character maps to <undefined>
2025-03-11 16:14:39,458 INFO    MainThread:25652 [wandb_init.py:init():896] updated telemetry
2025-03-11 16:14:39,464 INFO    MainThread:25652 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-11 16:14:39,923 INFO    MainThread:25652 [wandb_init.py:init():995] starting run threads in backend
2025-03-11 16:14:40,094 INFO    MainThread:25652 [wandb_run.py:_console_start():2377] atexit reg
2025-03-11 16:14:40,094 INFO    MainThread:25652 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-11 16:14:40,095 INFO    MainThread:25652 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-11 16:14:40,095 INFO    MainThread:25652 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-11 16:14:40,099 INFO    MainThread:25652 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-11 16:17:25,191 INFO    MainThread:25652 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-11 16:17:25,191 INFO    MainThread:25652 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-11 16:17:43,994 INFO    MainThread:25652 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-11 16:17:43,998 INFO    MainThread:25652 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-11 16:17:43,998 INFO    MainThread:25652 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-11 16:17:48,607 WARNING MsgRouterThr:25652 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "c:\Users\hause\OneDrive\01_Studium\02_Master\05_Masterarbeit\ball_env\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 258, in _read_packet_bytes
    data = self._sock.recv(self._bufsize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\hause\OneDrive\01_Studium\02_Master\05_Masterarbeit\ball_env\Lib\site-packages\wandb\sdk\interface\router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\hause\OneDrive\01_Studium\02_Master\05_Masterarbeit\ball_env\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\hause\OneDrive\01_Studium\02_Master\05_Masterarbeit\ball_env\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 262, in _read_packet_bytes
    raise SockClientClosedError from e
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\hause\OneDrive\01_Studium\02_Master\05_Masterarbeit\ball_env\Lib\site-packages\wandb\sdk\interface\router.py", line 70, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\hause\OneDrive\01_Studium\02_Master\05_Masterarbeit\ball_env\Lib\site-packages\wandb\sdk\interface\router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-11 16:17:48,650 INFO    MsgRouterThr:25652 [mailbox.py:close():115] Closing mailbox, abandoning 1 handles.
